services:
  # A Docker web service
  - type: server
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn config.app:app --host 0.0.0.0 --port $PORT


    
# uvicorn main:app --host 0.0.0.0 --port $PORT